print(918273645*99*88*77*66*55*44*33*22*11) 
#this_is_the_ratio_of_much_time_i_spend_saying_that_i_am_going_to_do_my_homework_versus_how_long_i_actually_spend_doing_my_homework
#i_chose_this_name_for_the_file_because_this_is_my_reaction_every_time_i_find_out_how_long_i_procrastinated_doing_my_homework_and_realization_finally_kicks_in
